name: "Pull Request Docs Check"

on: 
  pull_request:
  workflow_dispatch:

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        build-command: "sphinx-build -b html source/ build/"
