name: "Deploy to AWS s3 bucket on PR merge"
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy_s3:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        build-command: "sphinx-build -b html source/ build/"
        
    - uses: actions/checkout@v1
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.S3_BUCKET_REGION }}
        SOURCE_DIR: 'build'      # optional: defaults to entire repository
