name: "Pull Request Docs Check"

on: 
  pull_request:
  workflow_dispatch:

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        build-command: "sphinx-build -b html source/ build/"

  # deploy_s3:
  #   needs: build_docs
  #   runs-on: ubuntu-latest
  #   steps:
    - uses: actions/checkout@v1
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.S3_BUCKET_REGION }}
        SOURCE_DIR: 'build'      # optional: defaults to entire repository
