name: "Pull Request Docs Check"
on: 
  pull_request
  workflow_dispatch:

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        build-command: "sphinx-build -b html source/ build/"

  deploy_s3:
    needs: build_docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync to S3
        uses: raulanatol/aws-s3-docker-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.S3_BUCKET_REGION }}
          AWS_BUCKET_NAME: ${{ secrets.S3_BUCKET }}
          SOURCE: build/
          TARGET: 
          WITH_DELETE: false
          WITH_CLOUD_FRONT_INVALIDATION: true
          AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          AWS_CLOUDFRONT_INVALIDATION_PATH: /
